server:
  port: 85


spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: assignment
  cloud:
    gateway:
      routes:
        - id: sms -service
          uri: http://localhost:84/sms/
          predicates:
          - Path=/sms/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 4
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedTokens: 1
        - id: email -service
          uri: http://localhost:84/email/
          predicates:
            - Path=/email/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1